[package]
name = "Edust"
version = "0.1.0"
edition = "2024"

[dependencies]
cranelift = "0.109"
cranelift-module = "0.109"
cranelift-jit = "0.109"
cranelift-native = "0.109"
target-lexicon = "0.12"

[lib]
name = "edust"
path = "src/lib.rs"

[[bin]]
name = "edustc"
path = "src/main.rs"